# Generated by Django 5.0.3 on 2024-04-02 14:07

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Movies',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=500)),
                ('description', models.TextField()),
                ('language', models.CharField(max_length=500)),
                ('release_date', models.DateField()),
                ('director', models.CharField(max_length=500)),
                ('actor', models.CharField(max_length=500)),
                ('poster_url', models.URLField()),
            ],
        ),
    ]
