# Generated by Django 5.0.3 on 2024-04-02 14:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Admin_page', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='movies',
            old_name='actor',
            new_name='actors',
        ),
        migrations.AlterField(
            model_name='movies',
            name='poster_url',
            field=models.URLField(max_length=500),
        ),
    ]
