# Generated by Django 5.0.3 on 2024-04-05 13:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Admin_page', '0002_rename_actor_movies_actors_alter_movies_poster_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='movies',
            name='price',
            field=models.DecimalField(decimal_places=2, default=150, max_digits=10),
        ),
    ]
