# Generated by Django 5.0.3 on 2024-04-09 06:55

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Admin_page', '0003_movies_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='movies',
            name='time',
            field=models.TimeField(default=datetime.time(14, 0)),
        ),
    ]
