# Generated by Django 5.0.3 on 2024-04-04 10:50

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ticketBooking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=500)),
                ('date', models.DateField()),
                ('time', models.TimeField()),
                ('seat', models.DecimalField(decimal_places=0, max_digits=10)),
                ('price', models.DecimalField(decimal_places=2, default=150, max_digits=10)),
            ],
        ),
    ]
