# Generated by Django 5.0.3 on 2024-04-05 11:50

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_page', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='ticketbooking',
            name='booking_id',
            field=models.UUIDField(default=uuid.uuid4, editable=False),
        ),
        migrations.AddField(
            model_name='ticketbooking',
            name='quantity',
            field=models.IntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='ticketbooking',
            name='seat',
            field=models.CharField(max_length=500),
        ),
    ]
