# Generated by Django 5.0.3 on 2024-04-06 05:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_page', '0002_ticketbooking_booking_id_ticketbooking_quantity_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='ticketbooking',
            name='total_price',
            field=models.DecimalField(decimal_places=2, default=150, max_digits=10),
        ),
    ]
