# Generated by Django 5.0.3 on 2024-04-07 10:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_page', '0004_ticketbooking_user'),
    ]

    operations = [
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order_id', models.CharField(default='', max_length=100)),
                ('amount', models.IntegerField(default=1)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
