# Generated by Django 5.0.3 on 2024-04-10 17:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_page', '0005_payment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ticketbooking',
            name='time',
            field=models.CharField(max_length=500),
        ),
    ]
